FROM nvidia/cuda:11.8.0-base-ubuntu20.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
        git \
        python3-pip \
        python3-dev \
        python3-opencv \
        libglib2.0-0


# Upgrade pip
RUN python3 -m pip install --upgrade pip

# Install PyTorch and torchvision
RUN pip3 install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118

RUN pip install torch-cluster -f https://data.pyg.org/whl/torch-2.0.0+cu118.html
RUN pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+cu118.html
RUN pip install torch-sparse -f https://data.pyg.org/whl/torch-2.0.0+cu118.html
RUN pip install torch-geometric
RUN pip install wandb
RUN pip install tensorboard
### POINT TRANSFORMER ####
# refer https://github.com/traveller59/spconv
RUN pip install spconv-cu118  # choose version match your local cuda version
# Open3D (visualization, optional)
RUN pip install open3d
RUN pip install flash-attn --no-build-isolation
ADD . /app
# Set the working directory
WORKDIR /app
RUN pip install /app/.

# Set the entrypoint
ENTRYPOINT [ "/bin/bash" ]
